# Generated by Django 5.2 on 2025-04-09 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'immatriculation")),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('source', models.CharField(choices=[('CUSTOMER', 'Client'), ('ADMIN', 'Admin'), ('MECHANIC', 'Mécanicien')], default='ADMIN', max_length=10, verbose_name='Source')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_records', to='garage.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Relevé de Kilométrage',
                'verbose_name_plural': 'Relevés de Kilométrage',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
