# Generated by Django 5.2 on 2025-04-09 20:43

from django.db import migrations

# Function to create groups
def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Customers')
    Group.objects.get_or_create(name='Admins')

# Function to remove groups (for reverse migration)
def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Customers', 'Admins']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_vehicle_options_vehicle_owner'),
        # Add dependency on auth app's initial migration if necessary
        # to ensure Group model exists before we use it.
        # ('auth', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups), # Run our functions
    ]
