# Generated by Django 5.2 on 2025-04-09 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('garage', '0004_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format tunisien (ex: +216 20 123 456).', regex='^\\+216\\s?\\d{2}\\s?\\d{3}\\s?\\d{3}$')], verbose_name='Numéro de téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Client',
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro d'immatriculation doit être au format tunisien (ex: 123TU1234).", regex='^\\d{1,3}[Tt][Uu]\\d{1,4}$')], verbose_name="Numéro d'immatriculation"),
        ),
    ]
