# Generated by Django 5.2 on 2025-04-09 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_customerprofile_alter_vehicle_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='invoices/%Y/%m/', verbose_name='Fichier PDF')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant Final (DT)')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Date de Facture')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Upload")),
                ('service_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='garage.serviceevent', verbose_name='Intervention Associée')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='garage.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
